#!/bin/bash
set +e

profiles="$HOME/.ezsshfs"

function startfs() {
	if [ -f /tmp/ezsshfs-$1 ]
	then
		echo "Profile [$1] already started"
		exit 1
	fi

	if [ ! -f $profiles/$1 ]
	then
		echo "Can't file profile for '$1'"
		exit 1
	fi

	source $profiles/$1

	if [ ! -d $local_dir ]
	then
		mkdir $local_dir
	fi

	mnt=$( sshfs $host:$host_dir $local_dir -o Ciphers=arcfour,auto_cache,local,reconnect,defer_permissions,negative_vncache,volname=$1 2>&1 )

	if [ "$mnt" != "" ]
	then
		echo "Error: $mnt"
		exit 1
	fi

	touch /tmp/ezsshfs-$1
	echo "Starting [$1]"
}

function stopfs() {
	if [ ! -f $profiles/$1 ]
	then
		echo "Can't file profile for '$1'"
		exit 1
	fi

	if [ ! -f /tmp/ezsshfs-$1 ]
	then
		echo "Profile '$1' not currently mounted"
		exit 1
	fi

	source $profiles/$1

	umnt=$( umount $local_dir 2>&1 )

	if [ "$umnt" != "" ]
	then
		echo "Error: $umnt"
		if [[ "$umnt" == *"Resource busy"* ]]
		then
			echo "lsof for $local_dir:"
			lsof $local_dir | egrep -v '^lsof|egrep'
		fi
		exit 1
	fi

	rm /tmp/ezsshfs-$1
	echo "Stopping [$1]"
}

# command switch
case "$2" in
  start)
	startfs $1
	;;
  stop)
	stopfs $1
	;;
  restart)
	stopfs $1
	startfs $1
	;;
  *)
	echo $"Usage: ezsshfs {start|stop|restart} [profile]"
	exit 1
esac
exit 0
